version: '3'

services:
# DATABASE
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: runprogram
    ports: 
      - 3306:3306

# WEBSITE
  web:
    build: .
    depends_on: 
      - db
    volumes: 
      - ./php/:/var/www/html/
    ports: 
      - 8100:80

# MYSQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8200:80
    links: 
      - db:db
    environment:
      MYSQL_ROOT_PASSWORD: 1234

# FTP services
  ftpd:
    image: stilliard/pure-ftpd:hardened
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./data:/home/exam
      - ./passwd:/etc/pure/pure-ftpd/passwd
    environment:
      FTP_USER_NAME: exam
      FTP_USER_PASS: 1234
      FTP_USER_HOME: /home/exam

# Email services
  maildev:
    image: maildev/maildev
    ports:
      - "8300:80"
      - "25:25"
