version: '3'

services: 
    web:
        build: 
        volumes: 
          - ./www/:/var/www/htmp/
        ports: 
          - 8000:80
        depends_on: 
          - db
    db:
      image: mysql:5.7
      ports: 
      - 3306:3306
      environment: 
       MYSQL_ROOT_PASSWORD: 1234
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports: 
       - 8100:80
      environment: 
       MYSQL_ROOT_PASSWORD: 1234
       links: 
        - db:db